Include a check for the bitrot executable

diff --git a/new-md5 b/new-md5
--- a/new-md5
+++ b/new-md5
@@ -134,6 +134,11 @@ dir="$2"
 # Check whether to use bitrot or not
 use_bitrot=false
 if [[ "$3" == "--bitrot" ]]; then
+    if ! type bitrot > /dev/null 2>&1; then
+        echo "executable 'bitrot' not found, exiting."
+        echo "install instructions: https://pypi.org/project/bitrot/"
+        exit 1
+    fi
     use_bitrot=true
 fi
 
